import type { Database } from '@ansvar/mcp-sqlite';

export interface ResponseMetadata {
  data_freshness: DataFreshness;
  disclaimer: string;
  source_authority: SourceAuthority;
  coverage_gaps: string[];
  ai_disclosure: string;
}

export interface DataFreshness {
  statute_last_updated: string | null;
  staleness_warning: string | null;
}

export interface SourceAuthority {
  primary_source: string;
  authority_level: 'official' | 'community-maintained';
  verification_required: string;
}

export function generateResponseMetadata(db?: Database): ResponseMetadata {
  const dataFreshness = db ? getDataFreshness(db) : getEmptyDataFreshness();
  return {
    data_freshness: dataFreshness,
    disclaimer: 'NOT LEGAL ADVICE. This tool is for research purposes only. Always verify citations with official sources (uscode.house.gov, official state legislative portals) before relying on them in legal matters.',
    source_authority: {
      primary_source: 'US Code (uscode.house.gov) for federal statutes; official state legislative portals for state law',
      authority_level: 'official',
      verification_required: 'ALWAYS cross-check with official sources before using in professional legal work.',
    },
    coverage_gaps: [
      'Not all 50 states may have full coverage (expanding incrementally)',
      'Federal coverage limited to cyber/privacy titles (6, 15, 18, 42, 44, 47)',
      'Case law not included',
      'Regulatory guidance not included',
      'State-level comparison data may be incomplete',
    ],
    ai_disclosure: 'AI-assisted legal research tool. Results generated by algorithmic search and may contain errors or omissions. Human review required before professional use.',
  };
}

function getEmptyDataFreshness(): DataFreshness {
  return {
    statute_last_updated: null,
    staleness_warning: 'Data freshness information unavailable',
  };
}

function getDataFreshness(db: Database): DataFreshness {
  let statuteLastUpdated: string | null = null;
  try {
    const row = db.prepare(`SELECT MAX(created_at) as max_date FROM legal_documents WHERE status = 'in_force' AND created_at IS NOT NULL`).get() as { max_date: string | null } | undefined;
    statuteLastUpdated = row?.max_date || null;
  } catch { /* ignore */ }

  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  const warnings: string[] = [];

  if (statuteLastUpdated) {
    const ts = new Date(statuteLastUpdated);
    if (ts < thirtyDaysAgo) {
      warnings.push(`Data is ${Math.floor((now.getTime() - ts.getTime()) / (24 * 60 * 60 * 1000))} days old`);
    }
  } else {
    warnings.push('Data update timestamp unavailable');
  }

  return {
    statute_last_updated: statuteLastUpdated,
    staleness_warning: warnings.length > 0 ? warnings.join('. ') : null,
  };
}

export interface ToolResponse<T> {
  results: T;
  _metadata: ResponseMetadata;
}
